apiVersion: v1
kind: Service
metadata:
  name: hello-samplekuber
  labels:
    app: hello-samplekuber
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: hello-samplekuber
    tier: hello-samplekuber
  type: NodePort

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-samplekuber
  labels:
    app: hello-samplekuber
spec:
  template:
    metadata:
      labels:
        app: hello-samplekuber
        tier: hello-samplekuber
    spec:
      containers:
      - image: 127.0.0.1:30400/hello-samplekuber:latest
        name: hello-samplekuber
        ports:
        - containerPort: 80